app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path("", views.home, name="home"),
    path("product-detail/", views.product_detail, name="product-detail"),
    path("cart/", views.add_to_cart, name="add-to-cart"),
    path("buy/", views.buy_now, name="buy-now"),
    path("profile/", views.profile, name="profile"),
    path("address/", views.address, name="address"),
    path("orders/", views.orders, name="orders"),
    path("changepassword/", views.change_password, name="changepassword"),
    path("mobile/", views.mobile, name="mobile"),
    path("adminlogin/", views.adminlogin, name="adminlogin"),
    path("customerlogin/", views.customerlogin, name="customerlogin"),
    path("sellerlogin/", views.sellerlogin, name="sellerlogin"),
    path(
        "customerregistration/", views.customerregistration, name="customerregistration"
    ),
    path("sellerregistration/", views.sellerregistration, name="sellerregistration"),
    path("checkout/", views.checkout, name="checkout"),
]

seller/urls.py
from django.urls import path
from .import views

app_name="seller"
urlpatterns = [
    path('', views.home, name="home"),
    path('addproduct/', views.addbook, name="add"),
     path('product/', views.product, name="product"),
     path('edit/', views.edit, name="edit"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('seller/',include('seller.urls')),
    path('store_admin/',include('store_admin.urls')),
    path('customer/',include('customer.urls')),
    
   
]
    
    
    

seller/models.py
from django.db import models

# Create your models here.

seller/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request,'seller/seller_home.html')
def addbook(request):
    return render(request,'seller/seller_add.html')
def product(request):
    return render(request,'seller/seller_product.html')
def edit(request):
    return render(request,'seller/seller_edit.html')

seller/templates/seller/seller_add.html
{% extends 'seller/seller_master.html'%}
{% load static %}
{% block title %} Add Seller {% endblock title %}
{% block content %}

<div class="py-5 text-left">
    <h2>ADD PRODUCT</h2>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8 order-md-1">
            <form class="needs-validation" novalidate enctype="multipart/form-data" id="add_product"
                onload="resetSelection();">
                <div class="mb-3">
                    <label for="title">TITLE</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="title" placeholder="Title of the product" required>

                    </div>
                </div>
                <div class="mb-3">
                    <label for="regproductid">REGISTERED ID</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="regproductid" placeholder="Registered product id"
                            required>

                    </div>
                </div>
                <div class="mb-3">
                    <label for="description">DESCRIPTION </label>
                    <div class="input-group">
                        <textarea class="form-control" id="description" required></textarea>

                    </div>
                </div>
                <div class="mb-3">
                    <label for="customFile">Upload product pictures</label>
                    <input type="file" id="customFile" placeholder="choose" class="form-control" required>
                    <div class="invalid-feedback">
                        Please upload a picture.
                    </div>
                </div>
                <div class="mb-3">
                    <label for="price">Price</label>
                    <div class="input-group">
                        <input type="number" class="form-control" id="price" placeholder="₹ 0.0" required>
                        <div class="invalid-feedback">
                            Please enter the price.
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="quantity">Quantity</label>
                    <div class="input-group">
                        <input type="number" class="form-control" id="quantity" placeholder="Available quantity"
                            required>
                        <div class="invalid-feedback">
                            Please enter the quantity.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-6">
                        <label for="weight">Weight</label>
                        <div class="input-group">
                            <input type="number" class="form-control" id="weight" placeholder="0.0" required>
                            <div class="invalid-feedback">
                                Please enter the weight of the product.
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="weightunit">Weight unit</label>
                        <select class="custom-select d-block w-100 form-control" id="weightunit" required>
                            <option value="">Choose</option>
                            <option>kg</option>
                            <option>g</option>
                            <option>lb</option>
                            <option>oz</option>
                        </select>

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-6">
                        <label for="weightunit">MRP</label>

                        <div class="input-group">
                            <input type="number" class="form-control" id="weight" placeholder="" required>

                        </div>
                    </div>
                    <div class="col-md-6 mb-6">
                        <label for="weightunit">MANUFACTURE YEAR</label>

                        <div class="input-group">
                            <input type="number" class="form-control" id="weight" placeholder="" required>

                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-6 mt-3">
                        <label for="weightunit">PRODUCT QUANTITY</label>
                        <div class="input-group">

                            <input type="number" class="form-control" id="weight" placeholder="" required>

                        </div>
                    </div>
                    <div class="col-md-6 mb-6 mt-3">
                        <label for="weightunit">PRODUCT RATE</label>
                        <div class="input-group">
                            <input type="number" class="form-control" id="weight" placeholder="" required>

                        </div>
                    </div>



                    <div class="col-md-6">

                        <label for="category">CATEGORIES</label>
                        <select class="custom-select d-block w-100" id="category" size="1"
                            onchange="makeSubmenu(this.value);" required>
                            <option value="" disabled selected>Choose</option>
                            <option>WOMEN WEAR</option>
                            <option>MENS WEAR</option>
                            <option>new-arrivals</option>
                            <option>bestsellers</option>

                        </select>

                    </div>
                </div>


                <div class="row">
                    <div class="col-md-6 mb-6">
                        <label for="vendor">SELLER</label>
                        <div class="input-group">
                            <input type="text" class="form-control" id="brand" placeholder="" required>
                            <div class="invalid-feedback">
                                Please enter the brand name.
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2 mb-3">
                        <label for="status">Status</label>
                        <select class="custom-select d-block w-100" id="status" required>
                            <option value="">Choose</option>
                            <option>Active</option>
                            <option>Draft</option>
                        </select>

                    </div>
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

seller/templates/seller/seller_edit.html
{% extends 'seller/seller_master.html'%}
{% load static %}
{% block title %} Edit Seller {% endblock title %}
{% block content %}


<div class="py-5 text-left">
    <h2>EDIT PRODUCT</h2>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8 order-md-1">
            <form class="needs-validation" novalidate enctype="multipart/form-data" id="add_product"
                onload="resetSelection();">
                <div class="mb-3">
                    <label for="title">TITLE</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="title" placeholder="Title of the product" required>

                    </div>
                </div>
                <div class="mb-3">
                    <label for="regproductid">REGISTERED ID</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="regproductid" placeholder="Registered product id"
                            required>

                    </div>
                </div>
                <div class="mb-3">
                    <label for="description">DESCRIPTION </label>
                    <div class="input-group">
                        <textarea class="form-control" id="description" required></textarea>

                    </div>
                </div>
                <div class="mb-3">
                    <label for="customFile">Upload product pictures</label>
                    <input type="file" id="customFile" placeholder="choose" class="form-control" required>
                    <div class="invalid-feedback">
                        Please upload a picture.
                    </div>
                </div>
                <div class="mb-3">
                    <label for="price">Price</label>
                    <div class="input-group">
                        <input type="number" class="form-control" id="price" placeholder="₹ 0.0" required>
                        <div class="invalid-feedback">
                            Please enter the price.
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="quantity">Quantity</label>
                    <div class="input-group">
                        <input type="number" class="form-control" id="quantity" placeholder="Available quantity"
                            required>
                        <div class="invalid-feedback">
                            Please enter the quantity.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-6">
                        <label for="weight">Weight</label>
                        <div class="input-group">
                            <input type="number" class="form-control" id="weight" placeholder="0.0" required>
                            <div class="invalid-feedback">
                                Please enter the weight of the product.
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="weightunit">Weight unit</label>
                        <select class="custom-select d-block w-100 form-control" id="weightunit" required>
                            <option value="">Choose</option>
                            <option>kg</option>
                            <option>g</option>
                            <option>lb</option>
                            <option>oz</option>
                        </select>

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-6">
                        <label for="weightunit">MRP</label>

                        <div class="input-group">
                            <input type="number" class="form-control" id="weight" placeholder="" required>

                        </div>
                    </div>
                    <div class="col-md-6 mb-6">
                        <label for="weightunit">MANUFACTURE YEAR</label>

                        <div class="input-group">
                            <input type="number" class="form-control" id="weight" placeholder="" required>

                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-6 mt-3">
                        <label for="weightunit">PRODUCT QUANTITY</label>
                        <div class="input-group">

                            <input type="number" class="form-control" id="weight" placeholder="" required>

                        </div>
                    </div>
                    <div class="col-md-6 mb-6 mt-3">
                        <label for="weightunit">PRODUCT RATE</label>
                        <div class="input-group">
                            <input type="number" class="form-control" id="weight" placeholder="" required>

                        </div>
                    </div>



                    <div class="col-md-6">

                        <label for="category">CATEGORIES</label>
                        <select class="custom-select d-block w-100" id="category" size="1"
                            onchange="makeSubmenu(this.value);" required>
                            <option value="" disabled selected>Choose</option>
                            <option>WOMEN WEAR</option>
                            <option>MENS WEAR</option>
                            <option>new-arrivals</option>
                            <option>bestsellers</option>

                        </select>

                    </div>
                </div>


                <div class="row">
                    <div class="col-md-6 mb-6">
                        <label for="vendor">SELLER</label>
                        <div class="input-group">
                            <input type="text" class="form-control" id="brand" placeholder="" required>
                            <div class="invalid-feedback">
                                Please enter the brand name.
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2 mb-3">
                        <label for="status">Status</label>
                        <select class="custom-select d-block w-100" id="status" required>
                            <option value="">Choose</option>
                            <option>Active</option>
                            <option>Draft</option>
                        </select>

                    </div>
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

seller/templates/seller/seller_home.html
{% extends 'seller/seller_master.html'%}
{% load static %}
{% block content %}
<h3>SELL PRODUCTS ONLINE ON CYBERSHOP</h3>
<div class="container" style="margin-top: 3em;">
    <div class="row">
       <div class="col-md-12" class="text-center">
           <h4>Why Sell PRODUCTS On CYBERSHOP?</h4>
       </div>
       
    <div class="row bg-warning text-center p-5 text-white border-bottom shadow">
        <h1> Learn More About Selling PRODUCTS</h1>
    
    </div>
    <div class="col-md-1"></div>
 
    <div class="col-md-1"></div>
    <div class=" text-left">
    <h5>How Do I Sell PRODUCTS Online?</h5>
{% comment %}   
    <h5>How Do I Sell Product Online?</h5> {% endcomment %}
    <br><p>To sell products online, begin by identifying the types of books you want to sell. Your store could sell a variety of books, or you could sell books centred around a specific topic like used books, textbooks, and even antique books. You can then use a Shopify theme to easily start a store and upload pictures and descriptions of your books in minutes.</p>
     <br><hr><br>
    
     <h5>Where Can I Sell product ONline?</h5><br>
     <p>Shopify is an excellent place to sell books online, as you’ll have complete control over your brand, marketing, and customer experience. Shopify can even help integrate with social media platforms like Facebook Marketplace to help drive additional sales.</p>
    <br><hr><br>
   
    <h5>Can I Sell product On Online product Store</h5><br>
    <p>Yes, many product store owners trust Shopify to power their online stores. With Shopify, merchants can benefit from over 6,000 Shopify apps to help modernize book shopping experiences. That includes offering your customers personalized book recommendations, running a store-linked email newsletter, and more.</p>
     <br><hr><br>
     
     <h5>How Do I Price product?</h5><br>
     <p>The best way to price your product is to look at what your competition is charging for the same books or similar books. You can then decide on whether your pricing strategy will seek to undercut your competition, or sell at a higher price. You’ll also need to factor in shipping costs, particularly when dealing with heavier books.</p>
     <br><hr>
    </div>
</div>

</div>
   
        
      

    
        
     
{% endblock %}

seller/templates/seller/seller_master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title>Seller | {% block title %} {% endblock title %}</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css" />
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="{% static 'assets/vendors/jvectormap/jquery-jvectormap.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/vendors/flag-icon-css/css/flag-icon.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.theme.default.min.css' %}" />
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <!-- endinject -->
  <!-- Layout styles -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
  <!-- End layout styles -->
  <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
</head>

<body>
  <div class="container-scroller">
    <!-- partial:partials/_sidebar.html -->
    <nav class="sidebar sidebar-offcanvas" id="sidebar">
      <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
        <a class="sidebar-brand brand-logo " style="color: white; text-decoration: none;"
          href="{% url 'seller:home' %}">SELLER</a>
        <a class="sidebar-brand brand-logo-mini" style="color: white; text-decoration: none;"
          href="{% url 'seller:home' %}">S</a>
      </div>
      <ul class="nav">
        <li class="nav-item profile">
          <div class="profile-desc">
            <div class="profile-pic">
              <div class="count-indicator">
                <img class="img-xs rounded-circle" src="{% static 'assets/images/faces/face15.jpg' %}" alt="" />
                <span class="count bg-success"></span>
              </div>
              <div class="profile-name">
                <h5 class="mb-0 font-weight-normal">AATHIRA</h5>
              </div>
            </div>
        </li>
        <li class="nav-item nav-category">
          <span class="nav-link">Navigation</span>
        </li>
        <li class="nav-item menu-items">
          <a class="nav-link" href="{% url 'seller:home' %}">
            <span class="menu-icon">
              <i class="mdi mdi-speedometer"></i>
            </span>
            <span class="menu-title">Home</span>
          </a>
        </li>
        <li class="nav-item menu-items">
          <a class="nav-link" href="{% url 'seller:product' %}">
            <span class="menu-icon">
              <i class="mdi mdi-speedometer"></i>
            </span>
            <span class="menu-title">All Product</span>
          </a>
        </li>

        <li class="nav-item menu-items">
          <a class="nav-link" href="{% url 'seller:add' %}">
            <span class="menu-icon">
              <i class="mdi mdi-speedometer"></i>
            </span>
            <span class="menu-title">Add Product</span>
          </a>
        </li>

        <li class="nav-item menu-items">
          <a class="nav-link" href="{% url 'seller:edit' %}">
            <span class="menu-icon">
              <i class="mdi mdi-speedometer"></i>
            </span>
            <span class="menu-title">Edit Product</span>
          </a>
        </li>
      </ul>
    </nav>


    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_navbar.html -->
      <nav class="navbar p-0 fixed-top d-flex flex-row">
        <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
          <a class="navbar-brand brand-logo-mini" href="{% url 'seller:home' %}"><img
              src="{% static 'assets/images/logo-mini.svg' %}" alt="logo" /></a>
        </div>
        <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
          </button>
          <ul class="navbar-nav w-100">
            <li class="nav-item w-100">
              <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
                <input type="text" class="form-control" placeholder="Search products">
              </form>
            </li>
          </ul>
          <ul class="navbar-nav navbar-nav-right">


            <li class="nav-item dropdown">
              <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
                <div class="navbar-profile">
                  <img class="img-xs rounded-circle" src="{% static 'assets/images/faces/face15.jpg '%}" alt="">
                  <p class="mb-0 d-none d-sm-block navbar-profile-name">AATHIRA</p>
                  <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                </div>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
                aria-labelledby="profileDropdown">
                <h6 class="p-3 mb-0">Profile</h6>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-dark rounded-circle">
                      <i class="mdi mdi-settings text-success"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <p class="preview-subject mb-1">Settings</p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-dark rounded-circle">
                      <i class="mdi mdi-logout text-danger"></i>
                    </div>
                  </div>
                  <div class="preview-item-content">
                    <p class="preview-subject mb-1">Log out</p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <p class="p-3 mb-0 text-center">Advanced settings</p>
              </div>
            </li>
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
            data-toggle="offcanvas">
            <span class="mdi mdi-format-line-spacing"></span>
          </button>
        </div>
      </nav>



      <div class="main-panel">
        <div class="content-wrapper">

          
              {% block content %}
              dfghjk
              {% endblock %}
           
        </div>
        <footer class="footer">
          <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © aathira.com
              2022</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Designed by Aathira Kedharam
            </span>
          </div>
        </footer>
      </div>


      <!-- partial:partials/_footer.html -->





    </div>
  </div>
  <!-- plugins:js -->
  <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page -->
  <script src="{% static 'assets/vendors/chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'assets/vendors/progressbar.js/progressbar.min.js' %}"></script>
  <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap.min.js' %}"></script>
  <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
  <script src="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.js' %}"></script>
  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="{% static 'assets/js/off-canvas.js' %}"></script>
  <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'assets/js/misc.js' %}"></script>
  <script src="{% static 'assets/js/settings.js' %}"></script>
  <script src="{% static 'assets/js/todolist.js' %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page -->
  <script src="{% static 'assets/js/dashboard.js' %}"></script>
  <!-- End custom js for this page -->
</body>

</html>

seller/templates/seller/seller_product.html
{% extends "seller/seller_master.html" %}
 {% load static %} 
 {% block title %} All Product {% endblock title %}
 {% block content %}


<script src="{% static 'seller/scripts/delete_product.js' %}"></script>
<nav class=" navbar-dark bg-light">
    <div class="container">
        <a class="navbar-brand text-dark font-weight-bold" href="#">Products</a>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        </div>
        <button class="btn btn-primary" id="menu-toggle">Add product</button>
    </div>
</nav>
<nav class=" navbar-expand-lg navbar-dark bg-light">
    <button class="navbar-toggler bg-dark" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link text-dark" href="#">All
                      <span class="sr-only">(current)</span>
                    </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Status
                    </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item text-dark" href="#">Active</a>
                    <a class="dropdown-item" href="#">Draft</a>
                    <a class="dropdown-item" href="#">Archieved</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="#">filter 3</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="#">filter 4</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
<div class="row text-center" style="padding-top: 26pt;">
   
    <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
            <img class="card-img-top" src="/media/{{ product.img }}">
            <div class="card-body">
                <h4 class="card-title">{{product.title}}</h4>
                <h6>{{product.quantity}} in stock</h6>
                <h6>Status : {{product.status}}</h6>
                <h6>Vendor : {{product.vendor}}</h6>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" id="edit" href="editProducts/{{ product.id }}">Edit</a>
                <button onclick="delete_product('{{ product.id }}')" class="btn btn-danger">Delete</button>
            </div>
        </div>
    </div>
    
</div>
{% endblock %}