app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path("", views.home, name="home"),
    path("product-detail/", views.product_detail, name="product-detail"),
    path("cart/", views.add_to_cart, name="add-to-cart"),
    path("buy/", views.buy_now, name="buy-now"),
    path("profile/", views.profile, name="profile"),
    path("address/", views.address, name="address"),
    path("orders/", views.orders, name="orders"),
    path("changepassword/", views.change_password, name="changepassword"),
    path("mobile/", views.mobile, name="mobile"),
    path("adminlogin/", views.adminlogin, name="adminlogin"),
    path("customerlogin/", views.customerlogin, name="customerlogin"),
    path("sellerlogin/", views.sellerlogin, name="sellerlogin"),
    path(
        "customerregistration/", views.customerregistration, name="customerregistration"
    ),
    path("sellerregistration/", views.sellerregistration, name="sellerregistration"),
    path("checkout/", views.checkout, name="checkout"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('seller/',include('seller.urls')),
    path('store_admin/',include('store_admin.urls')),
    path('customer/',include('customer.urls')),
    
   
]
    
    
    

app/templates/app/addtocart.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <h1 class="text-center mb-5"> cyberShopping Cart</h1>
  <div class="col-sm-8">
  <div class="card">
   <div class="card-body">
    <h3>Cart</h3>
    <div class="row">
     <div class="col-sm-3 text-center align-self-center"><img src="{% static 'app/images/1.jpg'%}" alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"> </div>
     <div class="col-sm-9">
      <div>
       <h5>Product 1</h5>
       <p class="mb-2 text-muted small">Description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quas, nihil vel velit sed, quos consequatur maiores odio libero eius est in mollitia quo minus dolorum culpa consectetur, ipsam unde!</p>
       <div class="my-3">
        <label for="quantity">Quantity:</label>
        <a class="minus-cart btn"><i class="fas fa-minus-square fa-lg"></i></a>
          <span id="quantity">3</span>
        <a class="plus-cart btn"><i class="fas fa-plus-square fa-lg"></i></a>
       </div> 
       <div class="d-flex justify-content-between">
        <a href="#" class="btn btn-sm btn-secondary mr-3">Remove item </a>
        <p class="mb-0"><span><strong>Rs. 110.00</strong></span></p>
       </div>
      </div>
     </div>
    </div>
    <hr class="text-muted">
    <div class="row my-5">
     <div class="col-sm-3 text-center align-self-center"> <img src="{% static 'app/images/2.jpg'%}" alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"></div>
     <div class="col-sm-9"> 
      <div>
       <h5>Product 2</h5>
       <p class="mb-2 text-muted small">Description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio corrupti repudiandae quas tenetur? Vel harum iste impedit ad cupiditate sint soluta consequuntur sed, enim, eligendi labore molestiae! Mollitia, ad exercitationem!</p>
       <div class="my-3">
        <label for="quantity">Quantity:</label>
        <a class="minus-cart btn"><i class="fas fa-minus-square fa-lg"></i></a>
          <span id="quantity">2</span>
        <a class="plus-cart btn"><i class="fas fa-plus-square fa-lg"></i></a>
       </div> 
       <div class="d-flex justify-content-between">
        <a href="#" class="btn btn-sm btn-secondary mr-3">Remove item </a>        
        <p class="mb-0"><span><strong>Rs. 320.00</strong></span></p>
       </div>
      </div>
     </div>
    </div>
   </div>
   </div>
  </div>

  <div class="col-sm-4">
   <div class="card">
    <div class="card-body">
      <h3>The Total Amount of</h3>
      <ul class="list-group">
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">Amount<span>Rs. 430.00</span></li>
       <li class="list-group-item d-flex justify-content-between align-items-center px-0">Shipping<span>Rs. 70.00</span></li>
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
        <div>
           <strong>Total</strong> <small>(including GST)</small>
         </div>
         <span><strong>Rs. 500.00</strong></span>
       </li>
      </ul>
      <div class="d-grid"><a href="{% url 'app:checkout' %}" class="btn btn-primary">Place Order</a></div>
    </div>
   </div>
  </div>
  
 </div>
</div>
<div class="container">
 <div class="row">
  <div class="col-sm-8">
   <div class="card">
    <div class="card-body">
      <h5 class="mb-4">We accept</h5>
      <img src="{% static 'app/images/payment.png' %}" alt="" class="img-fluid">
    </div>
  </div>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/adminlogin.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Admin Login</h3>
   <hr>
   <form action="" method="POST"  class="shadow p-5">
       {% csrf_token %}
    <div class="mb-3">
     <label for="exampleInputEmail1" class="form-label">Email</label>
     <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
     <label for="exampleInputPassword1" class="form-label">Password</label>
     <input type="password" class="form-control" name="password" id="exampleInputPassword1">
    </div>
    <small style="color:red;">{{error_msg}}</small>
    <small><a href="#">Forgot Password ?</a></small> <br>
    <input type="submit" class="btn btn-primary mt-4" value="Login">
    <br>
   </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!--Owl Carousel CSS-->
    <link rel="stylesheet" href="{% static 'app/css/owl.carousel.min.css' %}">

    <!--FontAwesome CSS-->
    <link rel="stylesheet" href="{% static 'app/css/all.min.css' %}">

    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">


    <title>cybershop | {% block title %} {% endblock title %} </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
     <div class="container">
       <a class="navbar-brand" href="/">cybershop</a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item">
             <a class="nav-link active" aria-current="page" href="/">Home</a>
           </li>
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle text-white" href="#" id="electronicsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               Electronics
             </a>
             <ul class="dropdown-menu" aria-labelledby="electronicsDropdown">
               <li><a class="dropdown-item" href="{% url 'app:mobile' %}">Mobile</a></li>
               <li><a class="dropdown-item" href="#">Laptop</a></li>
             </ul>
           </li>
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle text-white" href="#" id="fashionDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               Fashion
             </a>
             <ul class="dropdown-menu" aria-labelledby="fashionDropdown">
               <li><a class="dropdown-item" href="#">Top Wear</a></li>
               <li><a class="dropdown-item" href="#">Bottom Wear</a></li>
             </ul>
           </li>
         </ul>
         <form class="d-flex">
           <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
           <button class="btn btn-warning" type="submit">S</button>
         </form>
         <div>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item dropdown mx-2">
              <a class="nav-link dropdown-toggle text-white" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Shopx
              </a>
              <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                <li><a class="dropdown-item" href="{% url 'app:profile' %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'app:orders' %}">Orders</a></li>
                <li><a class="dropdown-item" href="{% url 'app:changepassword' %}">Change Password</a></li>
                <li><a class="dropdown-item" href="#">Logout</a></li>
              </ul>
            </li>
            <li class="nav-item mx-2">
             <a href="{% url 'app:add-to-cart' %}" class="nav-link text-white"><span class="badge bg-danger">4</span> Cart </a>
            
            <li class="nav-item dropdown mx-2">
             <a href="" class="nav-link dropdown-toggle text-white" role="button" data-bs-toggle="dropdown" aria-expanded="false">Login</a>
             <ul class="dropdown-menu" aria-labelledby="profileDropdown">
              <li><a class="dropdown-item" href="{% url 'app:customerlogin' %}">Customer Login</a></li>
              <li><a class="dropdown-item" href="{% url 'app:sellerlogin' %}">Seller Login</a></li>
             </ul>
            <li class="nav-item dropdown mx-2">
             <a href="" class="nav-link dropdown-toggle text-white" role="button" data-bs-toggle="dropdown" aria-expanded="false">Registration</a>
              <ul class="dropdown-menu" aria-labelledby="profileDropdown">
               <li><a class="dropdown-item" href="{% url 'app:customerregistration' %}">Customer Registration</a></li>
               <li><a class="dropdown-item" href="{% url 'app:sellerregistration' %}">Seller Registration</a></li>
              </ul>
            </li>
              

          </ul>
         </div>
       </div>
     </div>
    </nav>
    {% block banner_slider %} {% endblock banner_slider %}
    {% block livesale %} {% endblock livesale %}
    {% block main-content %} {% endblock main-content %}

    <!-- Start Footer -->
    <footer class="container-fluid bg-dark text-center p-2 mt-5">
        <small class="text-white">Copyright &copy; 2022 || Designed by aathirakedaharam || </small>
        <img src="{% static 'app/images/payment.png' %}" alt="" srcset="" class="img-fluid" height="2px">
    </footer> <!-- End Footer -->

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <script src="{% static 'app/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'app/js/all.min.js' %}"></script>
    <script src="{% static 'app/js/myscript.js' %}"></script>
  </body>
</html>

app/templates/app/buynow.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}BUY NOW{% endblock title %}
{% block main-content %}
Product Buy Now
{% endblock main-content %} 

app/templates/app/changepassword.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
 <h3>Welcome CYBERSHOP</h3>
  <div class="col-sm-2 border-end">
   <ul class="list-unstyled">
    {% comment %} <li class="d-grid"><a href="{% url 'profile' %}" class="btn btn-primary">Change Password</a></li> {% endcomment %}
   </ul>
  </div>
  <div class="col-sm-9 offset-sm-1">
   <form>
     <div class="mb-3">
       <label for="exampleInputEmail1" class="form-label">Email address</label>
       <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
     </div>
     <div class="mb-3">
       <label for="exampleInputPassword1" class="form-label">New Password</label>
       <input type="password" class="form-control" id="exampleInputPassword1">
     </div>
     <div class="mb-3">
       <label for="exampleInputPassword1" class="form-label">Confirm New Password</label>
       <input type="password" class="form-control" id="exampleInputPassword1">
     </div>
     <button type="submit" class="btn btn-primary">Submit</button>
   </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/checkout.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row mt-5">
  <div class="col-sm-6">
    <h4>Order Summary</h4>
    <hr>
      <div class="card mb-2">
        <div class="card-body">
          <h5>Product: Product 1</h5>
          <p>Quantity: 2</p>
          <p class="fw-bold">Price: 100.00</p>
        </div>
      </div>
    <small>Term and Condition: Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia, ullam saepe! Iure optio repellat dolor velit, minus rem. Facilis cumque neque numquam laboriosam, accusantium adipisci nisi nihil in et quis?</small>
  </div>
  <div class="col-sm-4 offset-sm-1">
    <h4>Select Shipping Address</h4>
    <hr>
    <form action="">
      <div class="card">
        <div class="card-body">
        <h5>AATHIRA</h5>
        <p>KOZHIKODE,KERALA</p>
        </div>
      </div>
        <div class="form-check mt-2 mb-5">
          <input class="form-check-input" type="radio" value="">
          <label class="form-check-label fw-bold" for="">
            Address: 1 </label>
        </div>
        <div class="text-end">
          <button type="submit" class="btn btn-warning mt-3 px-5 fw-bold">Continue</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock main-content %}

app/templates/app/customerlogin.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3> Customer Login</h3>
   <hr>
   <form action="" method="POST" novalidate class="shadow p-5">
    {% csrf_token %}
    
    <div class="mb-3">
     <label for="exampleInputEmail1" class="form-label">Email</label>
     <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
     <label for="exampleInputPassword1" class="form-label">Password</label>
     <input type="password" class="form-control" name="password" id="exampleInputPassword1">
     <small style="color: red;">{{msg}}</small>
    </div>
    <small><a href="#">Forgot Password ?</a></small> <br>
    <input type="submit" class="btn btn-primary mt-4" value="Login">
    <br>
    <div class="text-center text-primary fw-bold"><small>New to cyberhop?? <a href="{% url 'app:customerregistration' %}"
       class="text-danger">Create an Account</a> </small></div>
   </form>
  </div>
 </div>
</div>
 

{% endblock main-content %}

app/templates/app/customerregistration.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Customer Registration{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Customer Registration</h3>
   <hr>
  
   <form action="" method="POST" novalidate class="shadow p-5">
{% csrf_token %}
    <div class="mb-3">
     <label for="inputEmail4" class="form-label">Email</label>
     <input type="email" class="form-control" name="email" id="inputEmail4">
     <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
     <label for="inputPassword1" class="form-label">Password</label>
     <input type="password" class="form-control" name="password" id="inputPassword1">
    </div>
    <div class="mb-3">
     <label for="inputPassword2" class="form-label">Confirm Password</label>
     <input type="password" class="form-control" id="inputPassword2">
    </div>
    <small style="color:darkred">{{msg}}</small>
    <div class="text-center">
     <button type="submit" class="btn btn-danger">Submit</button>
    </div>
    <br>
    <div class="text-center text-primary fw-bold"><small>Existing User ? <a href="{% url 'app:customerlogin' %}"
       class="text-danger">Login Now</a> </small></div>
  
    <!-- <p class="alert alert-danger my-3"></p> -->

   </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Login</h3>
   <hr>
   <form action="" method="post" novalidate class="shadow p-5">
    <div class="mb-3">
     <label for="exampleInputEmail1" class="form-label">Email</label>
     <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
     <label for="exampleInputPassword1" class="form-label">Password</label>
     <input type="password" class="form-control" id="exampleInputPassword1">
    </div>
    <small><a href="#">Forgot Password ?</a></small> <br>
    <input type="submit" class="btn btn-primary mt-4" value="Login">
    <br>
    <div class="text-center text-primary fw-bold"><small>NEW TO CYBERSHOP?? <a href="{% url 'customerregistration' %}"
       class="text-danger">Create an Account</a> </small></div>
   </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/mobile.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <div class="col-sm-3">
   Side Bar for Mobile filter
  </div>
  <div class="col-sm-8 offset-sm-1">
   Mobile Product List
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/orders.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
 <h3>Welcome CYBERSHOP</h3>
  <div class="col-sm-2 border-end">
   <ul class="list-unstyled">
    <li class="d-grid"><a href="{% url 'app:orders' %}" class="btn btn-primary">Orders</a></li>
   </ul>
  </div>
  <div class="col-sm-9 offset-sm-1">
   <div class="row">
    <div class="col-sm-6">Order 1</div>
    <div class="col-sm-6">Order 2</div>
   </div>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/productdetails.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Product Detail{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <div class="col-sm-6 text-center align-self-center">
   <img src="{% static 'app/images/p7.jpg' %}" alt="" class="img-fluid img-thumbnail">
  </div>
  <div class="col-sm-5 offset-sm-1">
   <h2>Product Title: Product 1</h2>
   <hr>
   <p>Product Description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, at. Dignissimos rerum incidunt temporibus laudantium. Rem, eveniet corporis. Itaque delectus quae nesciunt nemo, maiores minus deserunt vel. Vero, nulla quisquam!</p> <br>
   <h4>Rs. 13999 <small class="fw-light text-decoration-line-through">15999</small></h4> <br>
   <a href="{% url 'app:add-to-cart' %}" class="btn btn-primary shadow px-5 py-2">Add to Cart</a>
   <a href="{% url 'app:buy-now' %}" class="btn btn-danger shadow px-5 py-2 ms-4">Buy Now</a>
   <h5 class="mt-5">Available Offers</h5>
   <ul>
    <li>Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit</li>
    <li>Special Price Get extra ₹3000 off (price inclusive of discount)</li>
    <li>No cost EMI ₹1,667/month. Standard EMI also available</li>
    <li>Partner Offer ₹2000 Flipkart Gift Card on Every 1000th Transaction with a new Visa Debit/Credit Card</li>
   </ul>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/sellerlogin.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Seller Login</h3>
   <hr>
   <form action="" method="POST" novalidate class="shadow p-5">
    {% csrf_token %}
    <div class="mb-3">
     <label for="exampleInputEmail1" class="form-label">Email</label>
     <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
     <label for="exampleInputPassword1" class="form-label">Password</label>
     <input type="password" class="form-control" name="password" id="exampleInputPassword1">
     <small style="color: red;">{{msg}}</small>
    </div>
    <small><a href="#">Forgot Password ?</a></small> <br>
    <input type="submit" class="btn btn-primary mt-4" value="Login">
    <br>
    <div class="text-center text-primary fw-bold"><small>New to cyberhop?? <a href="{% url 'app:sellerregistration' %}"
       class="text-danger">Create an Account</a> </small></div>
   </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/sellerregistration.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Customer Registration{% endblock title %}
{% block main-content %}

<div id="page-content-wrapper">
    <div class="container-fluid" id="content">
<div class="container">

    <form class="needs-validation" method="POST">
      {% csrf_token %}
    
      <div class="row">

        <div class="col-md-4 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Payment information</span>
          </h4>
          <div class="mb-3">
            <label>Account holder name</label>
            <div class="input-group">
              <input type="text" class="form-control" id="username" name="acc_name" placeholder="" required>
              <div class="invalid-feedback" style="width: 100%;">
                please enter name of account holder
              </div>
            </div>
          </div>
          <div class="mb-3">
            <label for="title">Account number</label>
            <div class="input-group">
              <input type="text" class="form-control" id="username" name="acc_number" placeholder="" required>
              <div class="invalid-feedback" style="width: 100%;">
                Product account number
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 mb-6">
              <label for="title">Branch</label>
              <div class="input-group">
                <input type="text" class="form-control" id="username" placeholder="" name="branch"  required>
                <div class="invalid-feedback" style="width: 100%;">
                  Please enter branch
                </div>
              </div>
            </div>

            <div class="col-md-6 mb-6">
              <label for="state">IFSC number</label>
              <input type="text" class="form-control" id="weight" name="ifsc" placeholder="">
              <div class="invalid-feedback">
                Please enter IFSC number
              </div>
            </div>
          </div>
          

        </div>

        <div class="col-md-8 order-md-1">
          <!-- <h4 class="mb-3">Billing address</h4> -->

          <div class="row">
            <div class="col-md-6 mb-6">
              <label for="state">First name</label>
              <input type="text" class="form-control" id="weight" name="first_name" placeholder="First name">
              <div class="invalid-feedback">
                Please enter first name
              </div>
            </div>

            <div class="col-md-6 mb-6">
              <label for="state">Last name</label>
              <input type="text" class="form-control" id="weight" name="last_name" placeholder="Last name">
              <div class="invalid-feedback">
                Please enter last name
              </div>
            </div>
          </div>
          <div class="mb-3">
            <label for="description" required>Address </label>
            <textarea class="form-control" name="address" id="address"></textarea>
            <div class="invalid-feedback">
              Please enter your address
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 mb-4">
              <label for="state">City</label>
              <input type="text" class="form-control" id="weight" name="city" placeholder="City">
              <div class="invalid-feedback">
                Please enter City name
              </div>
            </div>

            <div class="col-md-4 mb-4">
              <label for="state">Country/Region</label>
              <input type="text" class="form-control" id="weight" name="country" placeholder="Country/Region">
              <div class="invalid-feedback">
                Please enter Country/Region
              </div>
            </div>
            <div class="col-md-4 mb-4">
              <label for="state">Pin</label>
              <input type="text" class="form-control" id="weight" name="pin" placeholder="Pin">
              <div class="invalid-feedback">
                Please enter Pincode
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 mb-6">
              <label for="title">Phone</label>
              <div class="input-group">
                <input type="text" class="form-control" id="username" name="phone" placeholder="Phone number" required>
                <div class="invalid-feedback" style="width: 100%;">
                  Please enter your phone number
                </div>
              </div>
            </div>

            <div class="col-md-6 mb-6">
              <label for="state">Email</label>
              <input type="email" class="form-control" id="weight" name="email" placeholder="Email id">
              <div class="invalid-feedback">
                Please enter email
              </div>
            </div>
          </div>

          <div class="col-md-6 mb-6">
            <label for="title">Password</label>
            <div class="input-group">
              <input type="text" class="form-control" id="password" name="password" placeholder="" required>
              <div class="invalid-feedback" style="width: 100%;">
                Password
              </div>
            </div>

          <hr class="mb-4">
          <button class="btn btn-success btn-lg btn-block" type="submit">Save</button>

        </div>
      </div>
    </form>
  </div>
</div>
</div>
{% endblock main-content %}